### PR TITLE
Fix links to example code

### LINKED ISSUE #3: Link to code on Github is broken
Link such as: 

``` markdown
[3_temperature.rs](https://github.com/knurling-rs/knurling-sessions-20q4/blob/main/src/bin/3_temperature.rs).
```

in file https://github.com/knurling-rs/knurling-session-20q4/blob/main/src/sessions/internal_temp.md
are broken. I couldn't find the actual source file to correct it myself.

### PR DESCRIPTION
**Pull request by Urhengulas**
Fixes #3

### CODE REVIEW

**Comment by Mirabellensaft** [comment]
The mdbook tries to open the relative links as mdbook pages, which ends up as 404. I don't know if this is a just deploy preview issue.

**Comment by Urhengulas** [comment]
The new solution uses `rustdoc_include`, which inlines an expandable code block. See https://rust-lang.github.io/mdBook/format/mdbook.html#including-a-file-but-initially-hiding-all-except-specified-lines. What do you think?

**Comment by japaric** [comment]
@Urhengulas could you please change this PR to use absolute links like it was in the beginning but that point into this public repo (instead of the archived private one)? Feel free to auto-merge (send to bors) that version. I would not change how the code is rendered in this PR; let's first fix the links.

**Comment by Mirabellensaft** [comment]
I like this format for the future: we could substitute the playgrounds with that, it seems way more comfortable for the future. But having direct links to the repo is more useful for providing the full solution

**Comment by Urhengulas** [comment]
> @Urhengulas could you please change this PR to use absolute links like it was in the beginning but that point into this public repo (instead of the archived private one)? Feel free to auto-merge (send to bors) that version. I would not change how the code is rendered in this PR; let's first fix the links.

Yeah.. I initially wanted to used relative links to enable the links to work locally, but seems you can't link to files outside of `src/`.

**Review by Mirabellensaft — APPROVED** [review]

**Pull request merged**
